import { Tree } from 'antd';
import { type OrgMember } from '../../../types/org';
import { OrgNode } from './OrgNode';

interface OrgChartProps {
  data: OrgMember;
  searchTerm: string;
}

export function OrgChart({ data, searchTerm }: OrgChartProps) {
  const renderTreeNodes = (node: OrgMember): any => ({
    title: <OrgNode member={node} searchTerm={searchTerm} />,
    key: node.id,
    children: node.children ? node.children.map(renderTreeNodes) : [],
  });

  return (
    /**
     * Renders the organizational chart using the Ant Design Tree component.
     * 
     * The Tree component is configured with the following properties:
     * - `treeData`: An array containing the hierarchical data structure of the organization.
     *   It is generated by mapping the `data` prop through the `renderTreeNodes` function.
     * - `defaultExpandAll`: A boolean that, when true, expands all tree nodes by default.
     * - `blockNode`: A boolean that, when true, makes the entire tree node clickable.
     * - `showLine`: A boolean that, when true, makes the entire tree node clickable.
     */
    <div className="flex justify-center pt-8 w-full overflow-x-auto">
      <Tree
        treeData={[renderTreeNodes(data)]}
        defaultExpandAll
        blockNode
      />
    </div>
  );
}